server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/isf_guatemala
spring.datasource.username=isf_admin
spring.datasource.password=IsF2024@Guatemala!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

